package modelo;
// Generated 20:00:38, 27 de feb. de 2023 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Cicloformativo generated by hbm2java
 */
@Entity
@Table(name = "cicloformativo", catalog="instituto")
public class Ciclo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9051396418957563231L;
	private int idCiclo;
	private String nombre;
	private Integer horas;

	public Ciclo() {
	}

	public Ciclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

	public Ciclo(int idCiclo, String nombreCiclo, Integer horas) {
		this.idCiclo = idCiclo;
		this.nombre = nombreCiclo;
		this.horas = horas;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY )
	@Column(name = "idCiclo", unique = true, nullable = false)
	public int getIdCiclo() {
		return this.idCiclo;
	}

	public void setIdCiclo(int idCiclo) {
		this.idCiclo = idCiclo;
	}

	@Column(name = "nombreCiclo", length = 100)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombreCiclo) {
		this.nombre = nombreCiclo;
	}

	@Column(name = "horas")
	public Integer getHoras() {
		return this.horas;
	}

	public void setHoras(Integer horas) {
		this.horas = horas;
	}

}
