package modelo;
// Generated 20:00:38, 27 de feb. de 2023 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Modulo generated by hbm2java
 */
@Entity
@Table(name = "modulo")
public class Modulo implements java.io.Serializable {

	private int idModulo;
	private String nombre;
	private Set<Profesor> profesors = new HashSet<Profesor>(0);

	public Modulo() {
	}

	public Modulo(int idModulo, String nombre) {
		this.idModulo = idModulo;
		this.nombre = nombre;
	}

	public Modulo(int idModulo, String nombre, Set<Profesor> profesors) {
		this.idModulo = idModulo;
		this.nombre = nombre;
		this.profesors = profesors;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY )
	@Column(name = "idModulo", unique = true, nullable = false)
	public int getIdModulo() {
		return this.idModulo;
	}

	public void setIdModulo(int idModulo) {
		this.idModulo = idModulo;
	}

	@Column(name = "nombre", nullable = false)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@ManyToMany(mappedBy = "modulos")
	public Set<Profesor> getProfesors() {
		return this.profesors;
	}

	public void setProfesors(Set<Profesor> profesors) {
		this.profesors = profesors;
	}

}
